config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#show'

  constraints format: :html do # respond_to の代わりに使ってみた。
    # For Teacher
    devise_for :teachers
    namespace :teachers do # namespace は単数形でも良かったかもな。
      root 'profile#show'
      resource :profile, controller: :profile, only: [:edit, :update]
      resource :schedules, only: [:edit, :update]
    end

    # For Student
    devise_for :students, controllers: {
      registrations: 'students/registrations'
    }
    namespace :students do
      root 'profile#show'
      resources :lessons, only: :index
    end

    # For Admin
    devise_for :admin_users, path: :admin
    namespace :admin do
      root 'teachers#index'
      resources :teachers
      resources :languages
    end
  end
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  include AvatarUploader::Attachment(:avatar)
  devise :database_authenticatable, :validatable

  has_many :teaching, dependent: :destroy
  has_many :teaching_languages, through: :teaching, source: :language
  has_many :schedules, dependent: :destroy

  with_options on: :update do
    validates :name, presence: true
    validates :avatar, presence: true
    validates :profile, presence: true
    validates :teaching_language_ids, presence: true
  end
end

app/controllers/admin/teachers_controller.rb
# frozen_string_literal: true

module Admin
  class TeachersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/students/profile_controller.rb
# frozen_string_literal: true

module Students
  class ProfileController < ApplicationController
    before_action :set_teacher

    def show
    end

    private

      def set_teacher
        @student = current_student
      end
  end
end

app/controllers/teachers/application_controller.rb
# frozen_string_literal: true

module Teachers
  class ApplicationController < ApplicationController
    before_action :authenticate_teacher!
  end
end

app/controllers/teachers/profile_controller.rb
# frozen_string_literal: true

module Teachers
  class ProfileController < ApplicationController
    before_action :set_teacher

    def show
    end

    def edit
    end

    def update
      if @teacher.update(teacher_params)
        redirect_to teachers_root_url,
                    notice: t('controllers.update.success', resource: Teacher.model_name.human)
      else
        render :edit
      end
    end

    private

      def set_teacher
        @teacher = current_teacher
      end

      def teacher_params
        params.require(:teacher).permit(:email, :name, :avatar, :profile, teaching_language_ids: [])
      end
  end
end

app/controllers/teachers/schedules_controller.rb
# frozen_string_literal: true

module Teachers
  class SchedulesController < ApplicationController
    before_action :set_default_language, only: :edit
    before_action :set_language, only: :update

    def edit
      @form = Schedules::Form.new(params[:start_date], @language, current_teacher)
    end

    def update
      @form = Schedules::Form.new(params[:start_date], @language, current_teacher)

      @form.save(schedule_params)
      redirect_to edit_teachers_schedules_url(start_date: params[:start_date],
                                              language: @language.name),
                  notice: t('controllers.update.success', resource: Schedule.model_name.human)
    end

    private

      def schedule_params
        params.require(:schedules)
      end

      def set_language
        @language = current_teacher.teaching_languages.find_by!(name: params[:language])
      end

      def set_default_language
        @language = params[:language].present? ? set_language : default_language
      end

      def default_language
        language = current_teacher.teaching_languages.first
        if language.blank?
          message = "レッスンスケジュールを登録するには#{Language.model_name.human}を１つ以上選択してください。"
          redirect_to(edit_teachers_profile_url, alert: message) && return
        end
        language
      end
  end
end

app/views/teachers/profile/edit.html.haml
= form_with model: @teacher, url: teachers_profile_path, local: true do |f|
  = render "shared/error_messages", object: f.object

  .field
    = f.label :email
    = f.email_field :email, class: "form-control"
  .field
    = f.label :name
    = f.text_field :name, class: "form-control"
  .field
    = f.hidden_field :avatar, value: @teacher.cached_avatar_data
    = f.label :avatar
    = f.file_field :avatar
    - if @teacher.avatar
      = image_tag @teacher.avatar_url(:square), class: "img-fluid", width: "200px"
  .field
    = f.label :profile
    = f.text_area :profile, class: "form-control"
  .field
    = f.label :teaching_language_ids
    = f.collection_check_boxes :teaching_language_ids, Language.all, :id, :name do |b|
      .form-check
        = b.check_box class: "form-check-input"
        = b.label class: "form-check-label" do
          = b.text

  .actions
    = f.submit "Save"

= link_to "Back", teachers_profile_path

app/views/teachers/profile/show.html.haml
= link_to "編集", edit_teachers_profile_path, class: "btn btn-primary float-right"

.card{ style: "width: 200px;" }
  = image_tag @teacher.avatar_url(:square), class: "card-img-top" if @teacher.avatar
  .card-body
    %h5.card-title= @teacher.name
    %p.card-text= nl2br @teacher.profile
  %ul.list-group.list-group-flush
    %li.list-group-item= @teacher.email
    %li.list-group-item= @teacher.teaching_languages.pluck(:name).join('、')